name: 'Site Publisher'
description: 'Publish site to indexer machine'
inputs:
  siteId:
    description: 'Site ID'
    required: true
  siteUrl:
    description: 'Site URL. Absolute path'
    required: true
  sitemapFile:
    description: 'Sitemap file. Relative path'
    required: true
outputs:
  siteUrl:
    description: 'Site URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
